import Head from "next/head";
import Navbar from "../components/Navbar";
import Grid from "../components/Grid";
import Price from "../components/Price";
import Newsletter from "../components/Newsletter";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hunter Nunnery | Software Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Grid />
      <Price />
      <Newsletter />
      <Contact />
    </div>
  );
}
